name: deploy to server

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: docker build 
        run: |
          docker build . --target prod --tag webapi:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: deployment
        run: |
          docker rm -f webApi 2> /dev/null || true
          docker run -d \
          --restart unless-stopped \
          --name webApi \
          --network towech-finance-network \
          -v /srv/logs/WebApi:/usr/app/logs \
          --env-file /srv/environments/WebAPI.env \
          webapi:latest
          docker image prune -f